# Generated by Django 2.2.3 on 2019-07-29 13:16

from django.db import migrations, models
import django.utils.timezone
import django_countries.fields
import embed_video.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('text', models.TextField()),
                ('image', sorl.thumbnail.fields.ImageField(default='images/default.jpg', upload_to='images/')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('link_name', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'ordering': ['published_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Athlet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
                ('surname', models.CharField(max_length=350)),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='images/')),
                ('web_site', models.CharField(blank=True, max_length=500)),
                ('web_site_name', models.CharField(blank=True, max_length=150)),
                ('e_mail', models.EmailField(blank=True, max_length=254)),
                ('date_of_birth', models.IntegerField(blank=True, null=True)),
                ('date_of_dearth', models.IntegerField(blank=True, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('sport', models.CharField(max_length=500)),
                ('diagnosis', models.CharField(max_length=500)),
                ('surgery', models.CharField(blank=True, max_length=500)),
                ('date_of_surgery', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('video', embed_video.fields.EmbedVideoField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['surname'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('text', models.TextField()),
                ('image', sorl.thumbnail.fields.ImageField(default='images/default.jpg', upload_to='images/')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('mood', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['published_at'],
                'abstract': False,
            },
        ),
    ]
