# Generated by Django 2.2.3 on 2019-07-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0002_auto_20190717_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='link_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
